import { StyleSheet } from "react-native";
import C from "./colors";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
    padding: 20,
    borderRadius: 15,
  },
  header: {
    color: C.text,
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: C.surface,
    color: C.text,
    borderRadius: 12,
    padding: 14,
    marginVertical: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: `${C.surface}80`,
    shadowColor: C.surface,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  area: {
    height: 160,
    textAlignVertical: "top",
    paddingTop: 12,
    lineHeight: 24,
  },
  btn: {
    backgroundColor: C.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 20,
    elevation: 3,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    alignItems: "center",
  },
  btnText: {
    color: C.bg,
    fontWeight: "700",
    fontSize: 16,
    textAlign: "center",
  },
  secondary: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: `${C.surface}50`,
  },
  secondaryText: {
    color: C.sub,
    fontSize: 14,
  },
});