import { StyleSheet } from "react-native";
import C from "./colors";

export default StyleSheet.create({
  card: {
    backgroundColor: C.surface,
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 16,
    padding: 18,
    elevation: 3,
    shadowColor: C.surface,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: `${C.surface}80`,
  },
  cardCompact: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  cardTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  cardBody: {
    color: C.sub,
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
  },
  meta: {
    color: C.sub,
    marginTop: 8,
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  searchBox: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: `${C.surface}20`,
  },
  searchInput: {
    backgroundColor: C.surface,
    color: C.text,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    elevation: 2,
    shadowColor: C.surface,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: `${C.surface}60`,
  },
  badge: {
    backgroundColor: "#16a34a",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    elevation: 2,
    shadowColor: "#16a34a",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  badgePending: {
    backgroundColor: "#f59e0b",
    shadowColor: "#f59e0b",
  },
  badgeSyncing: {
    backgroundColor: "#3b82f6",
    shadowColor: "#3b82f6",
  },
  badgeText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
    letterSpacing: 0.3,
  },
});